# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x06pubsub\"=\n\x0bPublication\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\t\";\n\tCondition\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x10\n\x08operator\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\"J\n\x0cSubscription\x12%\n\nconditions\x18\x01 \x03(\x0b\x32\x11.pubsub.Condition\x12\x13\n\x0bwindow_size\x18\x02 \x01(\x05\"\xd7\x01\n\rBrokerMessage\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.pubsub.BrokerMessage.MessageType\x12*\n\x0bpublication\x18\x02 \x01(\x0b\x32\x13.pubsub.PublicationH\x00\x12,\n\x0csubscription\x18\x03 \x01(\x0b\x32\x14.pubsub.SubscriptionH\x00\"0\n\x0bMessageType\x12\x0f\n\x0bPUBLICATION\x10\x00\x12\x10\n\x0cSUBSCRIPTION\x10\x01\x42\t\n\x07\x63ontentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUBLICATION']._serialized_start=25
  _globals['_PUBLICATION']._serialized_end=86
  _globals['_CONDITION']._serialized_start=88
  _globals['_CONDITION']._serialized_end=147
  _globals['_SUBSCRIPTION']._serialized_start=149
  _globals['_SUBSCRIPTION']._serialized_end=223
  _globals['_BROKERMESSAGE']._serialized_start=226
  _globals['_BROKERMESSAGE']._serialized_end=441
  _globals['_BROKERMESSAGE_MESSAGETYPE']._serialized_start=382
  _globals['_BROKERMESSAGE_MESSAGETYPE']._serialized_end=430
# @@protoc_insertion_point(module_scope)
